Do not validate the tibble
This causes an error in tibble-devel

    Error: Columns 1, 3 must be named

Because we set the column names in the following line.
Passing `validate = FALSE` fixes the issue.

Fixes #36